---
version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "00:00"
      timezone: "Australia/Sydney"
    assignees:
      - "MAHDTech"
    labels:
      - "chore"
      - "dependabot"
      - "dependencies"
    target-branch: "trunk"
    commit-message:
      prefix: "build"
      include: "scope"
    rebase-strategy: "auto"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directories:
      - "/"
      # Include composite actions as well as workflows.
      - "/composite/setup-nix"
      - "/composite/setup-nix-cache"
      - "/composite/setup-cache"
      - "/composite/setup-devenv"
      - "/composite/setup-trivy"
      - "/composite/free-disk-space"
      - "/composite/report-status"
      - "/composite/setup-cache/scripts/cache"
      - "/composite/setup-cache/scripts/cache-plan"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "00:00"
      timezone: "Australia/Sydney"
    assignees:
      - "MAHDTech"
    labels:
      - "actions"
      - "chore"
      - "dependabot"
      - "dependencies"
    target-branch: "trunk"
    commit-message:
      prefix: "build"
      include: "scope"
    rebase-strategy: "auto"
    open-pull-requests-limit: 5

  - package-ecosystem: "nix"
    directory: "/tests/fixtures/flakes"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "00:00"
      timezone: "Australia/Sydney"
    assignees:
      - "MAHDTech"
    labels:
      - "chore"
      - "dependabot"
      - "dependencies"
    target-branch: "trunk"
    commit-message:
      prefix: "build"
      include: "scope"
    rebase-strategy: "auto"
    open-pull-requests-limit: 5
