---
version: 2

updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      # Include composite actions as well as workflows.
      - "/setup-nix"
      - "/setup-cache"
      - "/setup-devenv"
      - "/setup-trivy"
      - "/free-disk-space"
      - "/internal/cache"
      - "/internal/cache-plan"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "00:00"
      timezone: "Australia/Sydney"
    assignees:
      - "MAHDTech"
    labels:
      - "actions"
      - "chore"
      - "dependabot"
      - "dependencies"
    target-branch: "trunk"
    commit-message:
      prefix: "github-actions"
    rebase-strategy: "auto"
    open-pull-requests-limit: 5
