---
name: "Test: Devenv Update PR Probe"
on:
  pull_request:
    branches:
      - tact-update-base-*
permissions:
  contents: read
jobs:
  # -------------------------------------------------
  # Observe the App Pull Request Event
  # -------------------------------------------------
  probe:
    name: Observe the App Pull Request Event
    runs-on: ${{ fromJSON(vars.TARS_REPORTING_RUNNER || vars.TARS_RUNNER_AMD64 || '"ubuntu-24.04"') }}
    steps:
      - id: probe
        name: Confirm the Pull Request Event
        run: echo 'App PR Checks Triggered'
